{"name": "test_C001003", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2", "trace": "self = <cases.test_2.Test_错误密码 object at 0x000001DE663AF9D0>\n\n    def test_C001003(self):\n        print('\\n用例C001003')\n>       assert 3 == 2\nE       assert 3 == 2\n\n..\\cases\\test_2.py:34: AssertionError"}, "attachments": [{"name": "stdout", "source": "3dd49bc9-3f38-4ef1-8b25-26233da0bf1e-attachment.txt", "type": "text/plain"}], "start": 1747564088244, "stop": 1747564088247, "uuid": "496a56c4-26cb-4be9-8e86-410b3180d402", "historyId": "6a7d7757a1bc1a8be185c256f64c83cf", "testCaseId": "6a7d7757a1bc1a8be185c256f64c83cf", "fullName": "cases.test_2.Test_错误密码#test_C001003", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_2"}, {"name": "subSuite", "value": "Test_错误密码"}, {"name": "host", "value": "DESKTOP-S9J93MS"}, {"name": "thread", "value": "73700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_2"}]}